### ISSUE TITLE
SpringBoot와 MySQL 연동

### ISSUE THREAD

**Issue by seoyeon0201** [Kakao-X-Goorm-DEEP-DIVE-course/1TEAM#16]
### 💼 작업 설명

API를 통해 가져온 데이터 중 필요한 데이터만 가져와 MySQL에 저장하는 로직

### ✅ To-do

- [x] MySQL Container 생성
- [x] MySQL 연동
- [x] HTTP 요청 시 데이터가 정상적으로 DB에 저장되는지 테스트
- [x] AWS RDS 연결
