### ISSUE TITLE
Kafka를 통한 Redis 저장 (실시간)

### ISSUE THREAD

**Issue by kpryu6** [Kakao-X-Goorm-DEEP-DIVE-course/1TEAM#17]
### 💼 작업 설명
1. 실시간 체결가 API를 통하여 얻은 데이터로 Topic을 생성
2. Kafka Producer를 통하여 메세지 브로커에 전달
3. Kafka Consumer가 메시지를 가져와 Redis에 넣어주는 작업

### ✅ To-do
- [x] 실시간 데이터의 한계로 테스트 코드 생성
- [x] Kafka Producer로 메세지 브로커에 데이터 전달
- [x] Kafka Consumer로 Redis에 데이터 넣는 작업
- [x] 실제 데이터 받아서 테스트
- [x] 데이터 유효성 검사 및 누락값 보완 작업
- [x] 중복값 Redis에 미할당 작업
- [x] TTL 작업
