### ISSUE TITLE
Kafka를 통한 MySQL 저장

### ISSUE THREAD

**Issue by seoyeon0201** [Kakao-X-Goorm-DEEP-DIVE-course/1TEAM#20]
### 💼 작업 설명
1. 실시간 체결가 API를 통하여 얻은 데이터로 Topic을 생성
2. Kafka Producer를 통하여 메세지 브로커에 전달
3. Kafka Consumer가 메시지를 가져와 Redis에 넣어주는 작업

### ✅ To-do

- [x] Kafka Producer로 메세지 브로커에 데이터 전달
- [x] Kafka Consumer로 MySQL에 저장
- [x] 실제 데이터로 테스트
- [x] 중복 데이터 처리
