### ISSUE TITLE
새로고침 없는 실시간 변동 프론트 (실시간 체결 API)

### ISSUE THREAD

**Issue by kpryu6** [Kakao-X-Goorm-DEEP-DIVE-course/1TEAM#21]
### 💼 작업 설명
실시간 체결 API, Kafka를 통해 실시간 변동 데이터들을 WebSocket으로 새로고침 없이 프론트엔드에 전달

### ✅ To-do

- [x] 프론트 UI (연희님이 해주심)
- [x] 프론트가 연결할 WebSocket 개발(Spring Boot)
- [x] 테스트 & 예외처리(WebSocket 미연결 시 기본 데이터 채우기 등)
