### ISSUE TITLE
국내주식 실시간 체결가 API 백엔드

### ISSUE THREAD

**Issue by naboyeong** [Kakao-X-Goorm-DEEP-DIVE-course/1TEAM#7]
### 💼 작업 설명
국내주식 실시간 체결가 API와 관련된 백엔드 작업

### ✅ To-do

- [x] Response 메시지 전처리
- [x] 주식 종목 구독 메서드
- [ ] DB 와 API 연결
